#!/usr/bin/env sh
#
# This will just change the theme of the config.h file
# and then build it
# 
# Configure yourself the colours
#
# BeyondMagic © 2021

origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P); cd $origin

[ "$1" = 'white' ] && {

    black='#151515';   black_b='#121212'
      red='#995464';     red_b='#DC322F'
    green='#649954';   green_b='#859900'
   yellow='#966C16';  yellow_b='#B58900'
     blue='#546499';    blue_b='#268BD2'
  magenta='#895499'; magenta_b='#D33682'
     cyan='#549989';    cyan_b='#2AA198'
    white='#111111';   white_b='#000000'

    bg='#ffffff'; sel='#ffffff'; selb='#111111'

} 

[ "$1" = 'black' ] && {

    black='#323033';   black_b='#424043'
      red='#EC5E66';     red_b='#EB3234'
    green='#009900';   green_b='#5CBF53'
   yellow='#FAC863';  yellow_b='#FAB42D'
     blue='#6699CC';    blue_b='#65D9EF'
  magenta='#D75F86'; magenta_b='#FA74CE'
     cyan='#357CD5';    cyan_b='#519FD1'
    white='#FDFCFD';   white_b='#FFFFFF'

    bg='#111111'; sel='#111111'; selb='#ffffff'

}

[ "$1" = 'black' ] || [ "$1" = 'white' ] || {

  echo "Y'all got some theme? Maybe black or white..."
  exit 1

}

# Build our new theme :)
[ $black ] && {

  sed -r \
    -e "s/\[0\] *= *\"#.*/[0] = \"$black\",/" \
    -e "s/\[1\] *= *\"#.*/[1] = \"$red\",/" \
    -e "s/\[2\] *= *\"#.*/[2] = \"$green\",/" \
    -e "s/\[3\] *= *\"#.*/[3] = \"$yellow\",/" \
    -e "s/\[4\] *= *\"#.*/[4] = \"$blue\",/" \
    -e "s/\[5\] *= *\"#.*/[5] = \"$magenta\",/" \
    -e "s/\[6\] *= *\"#.*/[6] = \"$cyan\",/" \
    -e "s/\[7\] *= *\"#.*/[7] = \"$white\",/" \
    -e "s/\[8\] *= *\"#.*/[8] = \"$black_b\",/" \
    -e "s/\[9\] *= *\"#.*/[9] = \"$red_b\",/" \
    -e "s/\[10\] *= *\"#.*/[10] = \"$green_b\",/" \
    -e "s/\[11\] *= *\"#.*/[11] = \"$yellow_b\",/" \
    -e "s/\[12\] *= *\"#.*/[12] = \"$blue_b\",/" \
    -e "s/\[13\] *= *\"#.*/[13] = \"$magenta_b\",/" \
    -e "s/\[14\] *= *\"#.*/[14] = \"$cyan_b\",/" \
    -e "s/\[15\] *= *\"#.*/[15] = \"$white_b\",/" \
    -e "s/\[256\] *= *\"#.*/[256] = \"$sel\",/" \
    -e "s/\[257\] *= *\"#.*/[257] = \"$selb\",/" \
    -e "s/\[258\] *= *\"#.*/[258] = \"$bg\",/" \
    config.h > ./config.new

  rm -rf config.h; mv config.new config.h

  doas -- make clean install

}
